packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^6.6.1
  '@eslint-react/eslint-plugin': ^2.3.13
  '@eslint/js': ^9.39.2
  '@hookform/resolvers': 5.2.2
  '@nestjs/axios': ^4.0.1
  '@nestjs/bullmq': ^11.0.4
  '@nestjs/cli': ^10.0.0
  '@nestjs/common': ^10.0.0
  '@nestjs/config': ^4.0.2
  '@nestjs/core': ^10.0.0
  '@nestjs/platform-express': ^10.0.0
  '@nestjs/platform-socket.io': 11.1.6
  '@nestjs/schedule': ^6.1.0
  '@nestjs/schematics': ^10.0.0
  '@nestjs/swagger': ^11.2.0
  '@nestjs/testing': ^10.0.0
  '@nestjs/websockets': ^11.1.6
  '@prisma/client': 6.17.1
  '@radix-ui/react-avatar': ^1.1.11
  '@radix-ui/react-dropdown-menu': 2.1.16
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-separator': ^1.1.8
  '@radix-ui/react-slot': 1.2.4
  '@reatom/core': ^1000.1.0
  '@reatom/npm-react': ^3.10.6
  '@reatom/react': ^1000.0.0
  '@socket.io/redis-adapter': ^8.3.0
  '@tailwindcss/postcss': 4.1.14
  '@types/cookie-parser': ^1.4.10
  '@types/express': ^4.17.17
  '@types/jest': ^29.5.2
  '@types/node': ^20
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  '@types/socket.io': ^3.0.2
  '@types/supertest': ^2.0.12
  '@vercel/analytics': ^1.5.0
  '@vitejs/plugin-react': ^5.1.1
  autoprefixer: ^10.4.23
  axios: ^1.13.2
  bullmq: ^5.66.4
  class-transformer: ^0.5.1
  class-validator: ^0.14.2
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  concurrently: ^8.2.2
  cookie: ^1.1.1
  cookie-parser: ^1.4.7
  dotenv: ^17.2.3
  eslint: ^9.39.2
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  globals: ^16.5.0
  husky: ^9.1.7
  i18next: ^25.7.3
  i18next-browser-languagedetector: ^8.2.0
  i18next-http-backend: ^3.0.2
  input-otp: 1.4.2
  ioredis: 5.8.1
  jest: ^29.5.0
  lint-staged: ^16.2.7
  lucide-react: 0.545.0
  next: 16.0.7
  next-intl: ^4.5.3
  postcss: ^8.5.6
  prettier: ^3.0.0
  prisma: ^6.17.1
  react: 19.2.0
  react-dom: 19.2.0
  react-hook-form: 7.66.0
  react-i18next: ^16.5.0
  react-router-dom: ^7.11.0
  redis: ^5.10.0
  reflect-metadata: ^0.1.13
  rxjs: ^7.8.1
  socket.io: ^4.8.1
  socket.io-client: 4.8.1
  source-map-support: ^0.5.21
  supertest: ^6.3.3
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.14
  ts-jest: ^29.1.0
  ts-loader: ^9.4.3
  ts-node: ^10.9.1
  tsconfig-paths: ^4.2.0
  tw-animate-css: ^1.4.0
  typescript: ^5.4.5
  typescript-eslint: ^8.50.1
  uuid: ^13.0.0
  vite: ^7.3.0
  zod: 4.1.13

catalogMode: prefer

catalogs:
  conflicts_typescript_h5:
    typescript: ^5
  conflicts_typescript_h5_1_3:
    typescript: ^5.1.3

overrides:
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2

shellEmulator: true

trustPolicy: no-downgrade
